### ISSUE TITLE
[bag]: wrap doesn't work

### ISSUE THREAD

**Issue by kaiphat** [rcarriga/nvim-notify#137]
![image](https://user-images.githubusercontent.com/53742299/193997336-b248a8cf-f5df-4521-b5fb-1c6ad5f84253.png)

**Comment by rcarriga** [comment]
The default renderer doesn't account for wrapped lines, nor could it because you it doesn't have the context of a window.
You could write a custom renderer assume that the text will be wrapped but instead I'd suggest doing something like this https://github.com/rcarriga/nvim-notify/issues/129#issuecomment-1245025162 which removes the complexity of calculating the wrapped line lengths

**Comment by kaiphat** [comment]
Thank you!
