### ISSUE TITLE
How not to get an BufWinLeave  autocmd triggered when a notification closes

### ISSUE THREAD

**Issue by michaelb** [rcarriga/nvim-notify#21]
Title says it.

I want to trigger an autocmd on every file type but this plugin broke the setup.

Could you tell me how to modify my (simplified):

`autocmd BufWinLeave * echo "autocmd triggered"`

so it doesn't get triggered every time a notification timeouts?

 I understand that it doesn't directly comes from nvim-notify's code, but for me it was a nasty 5h hunt for why this side-effect broke my setup, so a way to workaround this (quite counterintuitive) issue would be welcome for me, and potentially many others

**Comment by rcarriga** [comment]
That sounds like it's a pretty problematic autocmd to have at all but hey not going to question other's configs! :smile: Since I don't know what you're doing there's not much I can suggest specifically. You could change the pattern to be `?*` so there has to be at least a single character in the buffer name to be triggered
