### ISSUE TITLE
Allow to change the zindex of notifications

### ISSUE THREAD

**Issue by stsewd** [rcarriga/nvim-notify#26]
Hi, I have other plugins that make use of floating windows, and I'd like for notifications to be displayed on top of those.
This is possible with setting `zindex = 100` or similar value on all  animations, but I think this should be a global setting instead.

**Comment by stsewd** [comment]
Thanks, I think that works. Could be possible to provide a list of extra options or a callback function to configure this from the setup function instead of doing the overide manually?

**Comment by b0o** [comment]
This doesn't seem to be working for me.

I want the notification window to overlap some other floating windows which have a zindex of 100. I tried setting the notification's zindex to 200 in `on_open`, but the notification window is still appearing underneath the other floating window:

```lua
require('notify').setup {
  render = 'default',
  background_colour = '#252137',
  stages = 'slide',
  on_open = function(win)
    vim.api.nvim_win_set_config(win, { zindex = 200 })
  end,
}
```

I think this may be because the zindex is being set after the floating notification window has been opened. If I edit [`lua/notify/util/init.lua`](/rcarriga/nvim-notify/blob/master/lua/notify/util/init.lua) like so, it works how I expect:

```patch
diff --git a/lua/notify/util/init.lua b/lua/notify/util/init.lua
index ab04265..c0f72e7 100644
--- a/lua/notify/util/init.lua
+++ b/lua/notify/util/init.lua
@@ -87,6 +87,7 @@ function M.get_win_config(win)
 end
 
 function M.open_win(notif_buf, enter, opts)
+  opts.zindex = 200
   local win = vim.api.nvim_open_win(notif_buf:buffer(), enter, opts)
   -- vim.wo does not behave like setlocal, thus we use setwinvar to set local
   -- only options. Otherwise our changes would affect subsequently opened
```

Because of this, it would be nice to have a configuration option to directly set the zindex.

**Comment by rcarriga** [comment]
The zindex is not being set anywhere, this is a bug in a neovim and I've opened a report there https://github.com/neovim/neovim/issues/18142.

I've put in a workaround in the latest commit so you should see the desired behaviour now

**Comment by b0o** [comment]
Thank you! That did fix the issue for me.
