### ISSUE TITLE
Does timeout work? 

### ISSUE THREAD

**Issue by entropitor** [rcarriga/nvim-notify#36]
Is it possible the timeout feature doesn't work, no matter how I seem to pass it or to which value I set it, it seems to always only disappear after 5 seconds.

**Comment by rcarriga** [comment]
I see no issue with it locally, can you provide more details on how you're using it and what your config looks like?

**Comment by entropitor** [comment]
I use `vim.notify = require("notify")` but when I do 

```lua
require("notify").setup({
  timeout = 1000
})
```

It doesn't seem to do anything, neither for `vim.notify("This is an error message", "error", {timeout=1000})

**Comment by rcarriga** [comment]
Have you tried setting it to a very high number like 50000?

**Comment by entropitor** [comment]
A high number works, but so this setting cannot be used to lower the timeout? 

It seems the messages appear for 5 seconds + whatever the timeout is so if the timeout is 10 seconds, the message appears for 15 seconds

**Comment by rcarriga** [comment]
So the timeout only starts when the window animation has completed. Assuming you're using the default `fade_in_slide_out` stages, then it waits for the opacity to go to 100% which might seem like it happens earlier because it is using a spring algorithm and so the closer it gets, the slower the changes.

If you want to speed up the animation, you can use custom stages by either writing your own or editing the existing one.
For example:
```lua

  local stages = require("notify.stages").fade_in_slide_out
  stages[2] = function()
    return {
      opacity = { 100, frequency = 3 },
      col = { vim.opt.columns:get() },
    }
  end
  require("notify").setup({ stages = stages })
```
You should your timeout having a much more significant effect then.

You can see [the README](https://github.com/rcarriga/nvim-notify#animation-style) for details on how the animation works

**Comment by entropitor** [comment]
Yes, using the static stage, it's much faster. 👍
