### ISSUE TITLE
Feature request: make border style an option in setup()

### ISSUE THREAD

**Issue by FollieHiyuki** [rcarriga/nvim-notify#60]
`border = "rounded"` is currently hardcoded in different places.

It would be nice to have a variable, and even better if it is configurable with an option in `setup()` function.

**Comment by rcarriga** [comment]
You can already do this with the `on_open` setup option
```lua
  require("notify").setup({
    on_open = function (win)
      vim.api.nvim_win_set_config(win, { border = "double" })
    end,
  })

```

**Comment by FollieHiyuki** [comment]
Oh I didn't think about it :) Closing then.

Thanks for the help!

**Comment by danielo515** [comment]
Never thought about doing it this way

**Comment by joeyschoblaska** [comment]
@rcarriga If `{ border = "none" }` is set, it seems like the space for the border is still allocated in the rendered notifications. Is there a way to collapse these empty rows / cals so that multiple notifications take up less vertical space?

Current behavior:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/29129/212555050-b745ec5c-c2aa-40b8-b3c8-4345f1bba04c.png">

What I'd like to achieve:
<img width="1092" alt="Untitled 2" src="https://user-images.githubusercontent.com/29129/212555606-d8201a99-c6ac-47bb-b066-0ff999b934f6.png">

**Comment by joeyschoblaska** [comment]
Thanks for the detailed answer and the excellent plugin! The new compact rendering style looks great, too.
