### ISSUE TITLE
Crash: String cannot contain newlines

### ISSUE THREAD

**Issue by Mte90** [rcarriga/nvim-notify#65]
I am getting this error with the latest nvim nightly:

![immagine](https://user-images.githubusercontent.com/403283/156622147-d68e98c3-a1f7-4e91-9980-78892a62a61e.png)

**Comment by Mte90** [comment]
I did this patch but I don't think that is complete as I get some notification empty

https://github.com/rcarriga/nvim-notify/blob/master/lua/notify/render/default.lua#L35

```
  if type(notif.message) ~= "table" then
    api.nvim_buf_set_lines(bufnr, 2, -1, false, notif.message)

    api.nvim_buf_set_extmark(bufnr, namespace, 2, 0, {
      hl_group = highlights.body,
      end_line = 1 + #notif.message,
      end_col = #notif.message[#notif.message],
    })
  end
```

**Comment by rcarriga** [comment]
Can you show me the message that causes this error?

**Comment by Mte90** [comment]
In my case was something from phpactor but it was just `phpactor:` and the message was empty in the notification.

**Comment by rcarriga** [comment]
This behaviour occurs when a message is sent as a list of strings where there is a new line in the strings.

```lua
local notify = require("notify")

notify("This\nworks!")

notify({"This does not\nwork"})

```

 `nvim-notify` will split lines if given a string but not a list. Is this something you've written yourself to handle phpactor output? I ask because `vim.notify` isn't supposed to accept a list anyway so plugins using `vim.notify` should be joining the list

**Comment by Mte90** [comment]
I updated the plugin and I don't see anymore the issue (I removed my patch).
In case it is happening again I will reopen it with those information :-)
