### ISSUE TITLE
Enhancement: set where the notification appears

### ISSUE THREAD

**Issue by kdurant** [rcarriga/nvim-notify#7]

**Comment by rcarriga** [comment]
I don't think there would be any way to allow changing the the position that is more simple than currently exists, because if you change one position, all following positions would have to adapt too. There may be overlaps between some styles but I think the overhead of abstracting those overlaps would far outweigh the benefit.

I'm not stating there is no way though, happy to hear other thoughts but would definitely need some convincing arguments as IMO the current API is not too complicated :sweat_smile:

**Comment by akinsho** [comment]
Fair enough @rcarriga 👍🏿
