### ISSUE TITLE
 whcih font do you use in the show case pictures

### ISSUE THREAD

**Issue by charyxiao** [rcarriga/nvim-notify#92]
this font is so nice, but i can not figureout which font it is, Can you let me know if it's convenient。

**Comment by rcarriga** [comment]
Sure it's [JetBrains Mono patched with nerd fonts](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/font-info.md) :smile:

**Comment by charyxiao** [comment]
Thanks!

**Comment by Gargoth** [comment]
Hey! I'm not sure if this is the right place to ask but how were the outlines for the notifications in the showcase pictures not have broken lines? I also use the Jetbrains Mono Nerdfont but it looks different. I don't know if it matters but I use the windows terminal with WSL. Thanks!

![image](https://user-images.githubusercontent.com/51285956/173077431-8b09be54-73fc-4590-9660-c7e692dc26e5.png)
Showcase Picture (Above)

![image](https://user-images.githubusercontent.com/51285956/173077569-70f6e4b6-f648-4254-abf3-7f1fd3e44fce.png)
My Neovim notification (Above)

**Comment by Gargoth** [comment]
Yep they do show as three stacked lines, other ligatures work fine as well. 

![image](https://user-images.githubusercontent.com/51285956/173092985-2729a44b-da94-4724-96eb-dbadd1a6666b.png)

Since this is probably an issue specific to my side and not the font I'll just try to figure it out on my own. Thanks!
